using System.Security.Claims;
using System.Text;
using System.Text.RegularExpressions;

namespace FinanzasPersonales.Web.Services;

public class TraduccionService
{
    private static readonly Dictionary<string, Dictionary<string, string>> Traducciones = new(StringComparer.OrdinalIgnoreCase)
    {
        ["en"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Finanzas"] = "Finance",
            ["Control personal"] = "Personal control",
            ["Comprimir menu"] = "Collapse menu",
            ["Expandir menu"] = "Expand menu",
            ["Principal"] = "Main",
            ["Inicio"] = "Home",
            ["Documentacion"] = "Documentation",
            ["Analisis directivo"] = "Executive analysis",
            ["Asistente financiero"] = "Financial assistant",
            ["Calendario financiero"] = "Financial calendar",
            ["Gestion de Finanzas"] = "Finance Management",
            ["Analisis financiero"] = "Financial analysis",
            ["Registro rapido"] = "Quick entry",
            ["Movimientos"] = "Transactions",
            ["Metas de ahorro"] = "Savings goals",
            ["Recurrentes"] = "Recurring",
            ["Presupuestos"] = "Budgets",
            ["Importar"] = "Import",
            ["Cuentas"] = "Accounts",
            ["Categorias"] = "Categories",
            ["Gestion de Prestamos"] = "Loan Management",
            ["Analisis de prestamos"] = "Loan analysis",
            ["Prestamos"] = "Loans",
            ["Personas"] = "People",
            ["Gestion de Inversiones"] = "Investment Management",
            ["Analisis de inversiones"] = "Investment analysis",
            ["Portafolio"] = "Portfolio",
            ["Tipos de inversion"] = "Investment types",
            ["Administracion"] = "Administration",
            ["Usuarios"] = "Users",
            ["Integraciones"] = "Integrations",
            ["Tu progreso importa"] = "Your progress matters",
            ["Revisa tus metas cada mes."] = "Review your goals every month.",
            ["Registrar"] = "Add",
            ["Cambiar tema"] = "Switch theme",
            ["Mi cuenta"] = "My account",
            ["Cambiar clave"] = "Change password",
            ["Salir"] = "Sign out",
            ["Cambiar contrasena"] = "Change password",
            ["Contrasena actual"] = "Current password",
            ["Nueva contrasena"] = "New password",
            ["Confirmar nueva contrasena"] = "Confirm new password",
            ["Minimo 12 caracteres"] = "Minimum 12 characters",
            ["Mayuscula, minuscula, numero y simbolo"] = "Uppercase, lowercase, number and symbol",
            ["Cancelar"] = "Cancel",
            ["Guardar"] = "Save",
            ["Menu"] = "Menu",
            ["Buscar una opcion..."] = "Search an option...",
            ["Sin resultados"] = "No results",
            ["No tienes permiso para acceder a este modulo. Contacta al administrador de la suscripcion."] = "You do not have permission to access this module. Contact the subscription administrator.",
            ["El monto debe ser mayor que cero."] = "The amount must be greater than zero.",
            ["La cuenta origen y destino no pueden ser la misma."] = "The source and destination account cannot be the same.",
            ["Movimiento registrado."] = "Transaction saved.",
            ["Movimiento actualizado."] = "Transaction updated.",
            ["No se encontro el movimiento."] = "Transaction was not found.",
            ["Movimiento eliminado."] = "Transaction deleted.",
            ["Correo valido y nombre completo son obligatorios."] = "A valid email and full name are required.",
            ["Usuario no encontrado."] = "User not found.",
            ["Usuario actualizado."] = "User updated.",
            ["Pago de suscripcion registrado."] = "Subscription payment saved.",
            ["Cliente reactivado."] = "Customer reactivated.",
            ["El correo ya esta verificado."] = "The email is already verified.",
            ["El pago debe tener monto y periodo cubierto."] = "The payment must include amount and covered period.",
            ["Clientes activos"] = "Active customers",
            ["Ingreso esperado"] = "Expected income",
            ["Pagado este mes"] = "Paid this month",
            ["Clientes en mora"] = "Overdue customers",
            ["Cliente"] = "Customer",
            ["Suscripcion"] = "Subscription",
            ["Proximo pago"] = "Next payment",
            ["Estado"] = "Status",
            ["Ultimo acceso"] = "Last access",
            ["Nuevo cliente"] = "New customer",
            ["Clientes, acceso y suscripciones"] = "Customers, access and subscriptions",
            ["Administracion SaaS"] = "SaaS administration",
            ["Correo electronico"] = "Email",
            ["Nombre completo"] = "Full name",
            ["Contrasena inicial"] = "Initial password",
            ["Valor de suscripcion"] = "Subscription value",
            ["Ciclo"] = "Cycle",
            ["Inicio suscripcion"] = "Subscription start",
            ["Dias de gracia"] = "Grace days",
            ["Estado suscripcion"] = "Subscription status",
            ["Acceso activo"] = "Active access",
            ["Idioma"] = "Language",
            ["Moneda base"] = "Base currency",
            ["Zona horaria"] = "Time zone",
            ["Notas internas de suscripcion"] = "Internal subscription notes",
            ["Permisos del suscriptor"] = "Subscriber permissions",
            ["Registrar pago de suscripcion"] = "Register subscription payment",
            ["Fecha pago"] = "Payment date",
            ["Monto"] = "Amount",
            ["Periodo cubierto"] = "Covered period",
            ["Metodo"] = "Method",
            ["Referencia"] = "Reference",
            ["Notas"] = "Notes",
            ["Registrar pago"] = "Register payment",
            ["Ingresos"] = "Income",
            ["Gastos"] = "Expenses",
            ["Pagos tarjeta"] = "Card payments",
            ["Transferencias"] = "Transfers",
            ["Fecha"] = "Date",
            ["Tipo"] = "Type",
            ["Cuenta"] = "Account",
            ["Categoria"] = "Category",
            ["Descripcion"] = "Description",
            ["Desde"] = "From",
            ["Hasta"] = "To",
            ["Todos"] = "All",
            ["Todas"] = "All",
            ["Filtrar"] = "Filter",
            ["Rapido:"] = "Quick:",
            ["Este mes"] = "This month",
            ["Mes pasado"] = "Last month",
            ["Ultimos 3 meses"] = "Last 3 months",
            ["Este ano"] = "This year",
            ["No hay movimientos en este periodo."] = "There are no transactions in this period.",
            ["Registrar movimiento"] = "Add transaction",
            ["Editar movimiento"] = "Edit transaction",
            ["Moneda"] = "Currency",
            ["Tasa manual"] = "Manual rate",
            ["Opcional"] = "Optional",
            ["Medio de pago"] = "Payment method",
            ["Cuenta donde entra"] = "Destination account",
            ["Cuenta de donde sale"] = "Source account",
            ["Cuenta de donde sale el pago"] = "Payment source account",
            ["Tarjeta que pagas"] = "Card to pay",
            ["Descripcion (opcional)"] = "Description (optional)",
            ["Ingreso"] = "Income",
            ["Gasto"] = "Expense",
            ["Pago tarjeta"] = "Card payment",
            ["Transferencia"] = "Transfer",
            ["Tablero"] = "Dashboard",
            ["Saldo total"] = "Total balance",
            ["Ahorros"] = "Savings",
            ["Inversiones"] = "Investments",
            ["Total"] = "Total",
            ["Activo"] = "Active",
            ["Activa"] = "Active",
            ["Inactiva"] = "Inactive",
            ["Editar"] = "Edit",
            ["Eliminar"] = "Delete",
            ["Nuevo"] = "New",
            ["Nueva"] = "New",
            ["Crear"] = "Create",
            ["Actualizar"] = "Update",
            ["Detalle"] = "Detail",
            ["Resumen"] = "Summary",
            ["Historial"] = "History",
            ["Sin fecha"] = "No date",
            ["Sin pagos registrados."] = "No payments registered.",
            ["No hay eventos durante los proximos 60 dias."] = "No events in the next 60 days.",
            ["Proximos 60 dias"] = "Next 60 days",
            ["Agenda unificada"] = "Unified agenda",
            ["Tarjetas, gastos, cobros, metas y retornos en un solo lugar."] = "Cards, expenses, collections, goals and returns in one place.",
            ["Configuracion"] = "Settings",
            ["Preferencias"] = "Preferences",
            ["Actualizar preferencias"] = "Update preferences"
            ,
            ["Gestion premium"] = "Premium management",
            ["Control, claridad y crecimiento financiero"] = "Control, clarity and financial growth",
            ["Contrasena"] = "Password",
            ["Olvide mi contrasena"] = "Forgot my password",
            ["Ingresar"] = "Sign in",
            ["Acceso protegido con correo verificado, bloqueo por intentos y sesion segura."] = "Protected access with verified email, attempt lockout and secure session.",
            ["¿Quieres suscribirte?"] = "Want to subscribe?",
            ["Quieres suscribirte?"] = "Want to subscribe?",
            ["Acceso seguro"] = "Secure access",
            ["Recuperar contrasena"] = "Recover password",
            ["Te enviaremos un enlace de un solo uso si el correo existe."] = "We will send a one-time link if the email exists.",
            ["Enviar enlace"] = "Send link",
            ["Volver al ingreso"] = "Back to sign in",
            ["Proteccion de cuenta"] = "Account protection",
            ["Crear nueva contrasena"] = "Create new password",
            ["Usa una clave fuerte y unica para este sistema."] = "Use a strong and unique password for this system.",
            ["Confirmar contrasena"] = "Confirm password",
            ["Actualizar contrasena"] = "Update password",
            ["Preferencias actualizadas."] = "Preferences updated.",
            ["Olvidaste tu contrasena?"] = "Forgot your password?",
            ["Escribe tu correo registrado y te enviaremos un enlace seguro de un solo uso para crear una nueva contrasena."] = "Enter your registered email and we will send you a secure one-time link to create a new password.",
            ["Recuperar contrasena"] = "Recover password",
            ["Nuevo prestamo"] = "New loan",
            ["Antes de registrar un prestamo debes"] = "Before registering a loan you must",
            ["crear al menos una persona"] = "create at least one person",
            ["Todas las fechas"] = "All dates",
            ["Prestado desde"] = "Loaned from",
            ["Prestado hasta"] = "Loaned to",
            ["Limpiar filtros"] = "Clear filters",
            ["Capital prestado (activos)"] = "Loaned capital (active)",
            ["Saldo de capital por cobrar"] = "Capital balance receivable",
            ["Interes pendiente"] = "Pending interest",
            ["Capital"] = "Capital",
            ["Saldo"] = "Balance",
            ["Tasa"] = "Rate",
            ["Pagado"] = "Paid",
            ["Control"] = "Control",
            ["No tienes prestamos registrados."] = "You have no loans registered.",
            ["Fecha del prestamo"] = "Loan date",
            ["Interes mensual (%)"] = "Monthly interest (%)",
            ["Interes mensual ($)"] = "Monthly interest ($)",
            ["Dia de pago de interes"] = "Interest payment day",
            ["Pago del capital (si aplica)"] = "Capital payment date (if applicable)",
            ["Notas (opcional)"] = "Notes (optional)",
            ["Registrar prestamo"] = "Register loan",
            ["Capital y tasa deben ser validos."] = "Capital and rate must be valid.",
            ["Primero crea la persona en el modulo de Personas."] = "First create the person in the People module.",
            ["Prestamo registrado."] = "Loan registered.",
            ["Prestamo actualizado."] = "Loan updated.",
            ["Abono a capital registrado."] = "Capital payment registered.",
            ["Pago de interes registrado."] = "Interest payment registered.",
            ["Pago eliminado del historial."] = "Payment removed from history.",
            ["Prestamo eliminado con todo su historial."] = "Loan deleted with its full history.",
            ["Mi portafolio"] = "My portfolio",
            ["Controla capital, rentabilidad, vencimientos y valor de mercado."] = "Track capital, returns, maturities and market value.",
            ["Tipos"] = "Types",
            ["Analisis"] = "Analysis",
            ["Nueva inversion"] = "New investment",
            ["Debes"] = "You must",
            ["crear un tipo de inversion"] = "create an investment type",
            ["antes de registrar una inversion."] = "before registering an investment.",
            ["Activas"] = "Active",
            ["Cerradas"] = "Closed",
            ["Limpiar"] = "Clear",
            ["Capital aportado"] = "Contributed capital",
            ["Valor del portafolio"] = "Portfolio value",
            ["Ganancia real"] = "Real gain",
            ["Rentabilidad total"] = "Total return",
            ["Valor actual"] = "Current value",
            ["Ganancia"] = "Gain",
            ["Disponible desde"] = "Available from",
            ["Retorno:"] = "Return:",
            ["No tienes inversiones registradas"] = "You have no investments registered",
            ["Crea la primera para comenzar a medir rentabilidad y vencimientos."] = "Create the first one to start tracking returns and maturities.",
            ["Crear inversion"] = "Create investment",
            ["Nombre"] = "Name",
            ["Entidad / plataforma"] = "Entity / platform",
            ["Inicio"] = "Start",
            ["Capital inicial"] = "Initial capital",
            ["Rendimiento"] = "Return type",
            ["Fijo"] = "Fixed",
            ["Variable"] = "Variable",
            ["Tasa (%)"] = "Rate (%)",
            ["Periodo tasa"] = "Rate period",
            ["Anual"] = "Annual",
            ["Mensual"] = "Monthly",
            ["Fecha retorno"] = "Return date",
            ["Permanencia (meses)"] = "Minimum stay (months)",
            ["Penalidad retiro (%)"] = "Withdrawal penalty (%)",
            ["Color"] = "Color",
            ["Icono"] = "Icon",
            ["Renovacion automatica"] = "Automatic renewal",
            ["Guardar inversion"] = "Save investment",
            ["Revisa los datos de la inversion."] = "Review the investment data.",
            ["La fecha de retorno no puede ser anterior al inicio."] = "The return date cannot be before the start date.",
            ["Selecciona un tipo de inversion valido."] = "Select a valid investment type.",
            ["Inversion creada."] = "Investment created.",
            ["Inversion actualizada."] = "Investment updated.",
            ["La fecha no puede ser anterior al inicio de la inversion."] = "The date cannot be before the investment start date.",
            ["No puedes registrar un movimiento futuro."] = "You cannot register a future transaction.",
            ["Valor actual registrado."] = "Current value registered.",
            ["Valoracion eliminada."] = "Valuation deleted.",
            ["Inversion cerrada."] = "Investment closed.",
            ["Inversion reactivada."] = "Investment reactivated.",
            ["Inversion eliminada con su historial."] = "Investment deleted with its history."
            ,
            ["Recibimos una solicitud para restablecer tu contrasena."] = "We received a request to reset your password.",
            ["Restablecer contrasena"] = "Reset password",
            ["Este enlace vence en 30 minutos y solo puede usarse una vez."] = "This link expires in 30 minutes and can only be used once.",
            ["Verifica tu correo"] = "Verify your email",
            ["Confirma que este correo te pertenece para activar el acceso seguro."] = "Confirm that this email belongs to you to activate secure access.",
            ["Verificar correo"] = "Verify email",
            ["Este enlace vence en 24 horas."] = "This link expires in 24 hours.",
            ["Si el boton no funciona, copia este enlace:"] = "If the button does not work, copy this link:",
            ["Recordatorio:"] = "Reminder:",
            ["Tu gasto recurrente"] = "Your recurring expense",
            ["Tu ingreso recurrente"] = "Your recurring income",
            ["vence el"] = "is due on",
            ["Debes cobrar a"] = "You should collect from",
            ["Hola"] = "Hello",
            ["te recordamos el pago pendiente de tu prestamo. Gracias."] = "we remind you about your pending loan payment. Thank you.",
            ["La inversion"] = "The investment",
            ["tiene retorno esperado el"] = "has expected return on",
            ["Tu inversion"] = "Your investment"
        },
        ["pt"] = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Finanzas"] = "Financas",
            ["Control personal"] = "Controle pessoal",
            ["Comprimir menu"] = "Recolher menu",
            ["Expandir menu"] = "Expandir menu",
            ["Principal"] = "Principal",
            ["Inicio"] = "Inicio",
            ["Documentacion"] = "Documentacao",
            ["Analisis directivo"] = "Analise executiva",
            ["Asistente financiero"] = "Assistente financeiro",
            ["Calendario financiero"] = "Calendario financeiro",
            ["Gestion de Finanzas"] = "Gestao de Financas",
            ["Analisis financiero"] = "Analise financeira",
            ["Registro rapido"] = "Registro rapido",
            ["Movimientos"] = "Movimentacoes",
            ["Metas de ahorro"] = "Metas de poupanca",
            ["Recurrentes"] = "Recorrentes",
            ["Presupuestos"] = "Orcamentos",
            ["Importar"] = "Importar",
            ["Cuentas"] = "Contas",
            ["Categorias"] = "Categorias",
            ["Gestion de Prestamos"] = "Gestao de Emprestimos",
            ["Analisis de prestamos"] = "Analise de emprestimos",
            ["Prestamos"] = "Emprestimos",
            ["Personas"] = "Pessoas",
            ["Gestion de Inversiones"] = "Gestao de Investimentos",
            ["Analisis de inversiones"] = "Analise de investimentos",
            ["Portafolio"] = "Carteira",
            ["Tipos de inversion"] = "Tipos de investimento",
            ["Administracion"] = "Administracao",
            ["Usuarios"] = "Usuarios",
            ["Integraciones"] = "Integracoes",
            ["Tu progreso importa"] = "Seu progresso importa",
            ["Revisa tus metas cada mes."] = "Revise suas metas todos os meses.",
            ["Registrar"] = "Registrar",
            ["Cambiar tema"] = "Alterar tema",
            ["Mi cuenta"] = "Minha conta",
            ["Cambiar clave"] = "Alterar senha",
            ["Salir"] = "Sair",
            ["Cambiar contrasena"] = "Alterar senha",
            ["Contrasena actual"] = "Senha atual",
            ["Nueva contrasena"] = "Nova senha",
            ["Confirmar nueva contrasena"] = "Confirmar nova senha",
            ["Minimo 12 caracteres"] = "Minimo de 12 caracteres",
            ["Mayuscula, minuscula, numero y simbolo"] = "Maiuscula, minuscula, numero e simbolo",
            ["Cancelar"] = "Cancelar",
            ["Guardar"] = "Salvar",
            ["Menu"] = "Menu",
            ["Buscar una opcion..."] = "Buscar uma opcao...",
            ["Sin resultados"] = "Sem resultados",
            ["No tienes permiso para acceder a este modulo. Contacta al administrador de la suscripcion."] = "Voce nao tem permissao para acessar este modulo. Fale com o administrador da assinatura.",
            ["El monto debe ser mayor que cero."] = "O valor deve ser maior que zero.",
            ["La cuenta origen y destino no pueden ser la misma."] = "A conta de origem e destino nao podem ser a mesma.",
            ["Movimiento registrado."] = "Movimentacao registrada.",
            ["Movimiento actualizado."] = "Movimentacao atualizada.",
            ["No se encontro el movimiento."] = "Movimentacao nao encontrada.",
            ["Movimiento eliminado."] = "Movimentacao eliminada.",
            ["Correo valido y nombre completo son obligatorios."] = "Email valido e nome completo sao obrigatorios.",
            ["Usuario no encontrado."] = "Usuario nao encontrado.",
            ["Usuario actualizado."] = "Usuario atualizado.",
            ["Pago de suscripcion registrado."] = "Pagamento de assinatura registrado.",
            ["Cliente reactivado."] = "Cliente reativado.",
            ["El correo ya esta verificado."] = "O email ja esta verificado.",
            ["El pago debe tener monto y periodo cubierto."] = "O pagamento deve ter valor e periodo coberto.",
            ["Clientes activos"] = "Clientes ativos",
            ["Ingreso esperado"] = "Receita esperada",
            ["Pagado este mes"] = "Pago este mes",
            ["Clientes en mora"] = "Clientes em atraso",
            ["Cliente"] = "Cliente",
            ["Suscripcion"] = "Assinatura",
            ["Proximo pago"] = "Proximo pagamento",
            ["Estado"] = "Estado",
            ["Ultimo acceso"] = "Ultimo acesso",
            ["Nuevo cliente"] = "Novo cliente",
            ["Clientes, acceso y suscripciones"] = "Clientes, acesso e assinaturas",
            ["Administracion SaaS"] = "Administracao SaaS",
            ["Correo electronico"] = "Email",
            ["Nombre completo"] = "Nome completo",
            ["Contrasena inicial"] = "Senha inicial",
            ["Valor de suscripcion"] = "Valor da assinatura",
            ["Ciclo"] = "Ciclo",
            ["Inicio suscripcion"] = "Inicio da assinatura",
            ["Dias de gracia"] = "Dias de tolerancia",
            ["Estado suscripcion"] = "Estado da assinatura",
            ["Acceso activo"] = "Acesso ativo",
            ["Idioma"] = "Idioma",
            ["Moneda base"] = "Moeda base",
            ["Zona horaria"] = "Fuso horario",
            ["Notas internas de suscripcion"] = "Notas internas da assinatura",
            ["Permisos del suscriptor"] = "Permissoes do assinante",
            ["Registrar pago de suscripcion"] = "Registrar pagamento da assinatura",
            ["Fecha pago"] = "Data de pagamento",
            ["Monto"] = "Valor",
            ["Periodo cubierto"] = "Periodo coberto",
            ["Metodo"] = "Metodo",
            ["Referencia"] = "Referencia",
            ["Notas"] = "Notas",
            ["Registrar pago"] = "Registrar pagamento",
            ["Ingresos"] = "Receitas",
            ["Gastos"] = "Despesas",
            ["Pagos tarjeta"] = "Pagamentos de cartao",
            ["Transferencias"] = "Transferencias",
            ["Fecha"] = "Data",
            ["Tipo"] = "Tipo",
            ["Cuenta"] = "Conta",
            ["Categoria"] = "Categoria",
            ["Descripcion"] = "Descricao",
            ["Desde"] = "De",
            ["Hasta"] = "Ate",
            ["Todos"] = "Todos",
            ["Todas"] = "Todas",
            ["Filtrar"] = "Filtrar",
            ["Rapido:"] = "Rapido:",
            ["Este mes"] = "Este mes",
            ["Mes pasado"] = "Mes anterior",
            ["Ultimos 3 meses"] = "Ultimos 3 meses",
            ["Este ano"] = "Este ano",
            ["No hay movimientos en este periodo."] = "Nao ha movimentacoes neste periodo.",
            ["Registrar movimiento"] = "Registrar movimentacao",
            ["Editar movimiento"] = "Editar movimentacao",
            ["Moneda"] = "Moeda",
            ["Tasa manual"] = "Taxa manual",
            ["Opcional"] = "Opcional",
            ["Medio de pago"] = "Forma de pagamento",
            ["Cuenta donde entra"] = "Conta de entrada",
            ["Cuenta de donde sale"] = "Conta de saida",
            ["Cuenta de donde sale el pago"] = "Conta de onde sai o pagamento",
            ["Tarjeta que pagas"] = "Cartao que voce paga",
            ["Descripcion (opcional)"] = "Descricao (opcional)",
            ["Ingreso"] = "Receita",
            ["Gasto"] = "Despesa",
            ["Pago tarjeta"] = "Pagamento de cartao",
            ["Transferencia"] = "Transferencia",
            ["Tablero"] = "Painel",
            ["Saldo total"] = "Saldo total",
            ["Ahorros"] = "Poupanca",
            ["Inversiones"] = "Investimentos",
            ["Total"] = "Total",
            ["Activo"] = "Ativo",
            ["Activa"] = "Ativa",
            ["Inactiva"] = "Inativa",
            ["Editar"] = "Editar",
            ["Eliminar"] = "Excluir",
            ["Nuevo"] = "Novo",
            ["Nueva"] = "Nova",
            ["Crear"] = "Criar",
            ["Actualizar"] = "Atualizar",
            ["Detalle"] = "Detalhe",
            ["Resumen"] = "Resumo",
            ["Historial"] = "Historico",
            ["Sin fecha"] = "Sem data",
            ["Sin pagos registrados."] = "Sem pagamentos registrados.",
            ["No hay eventos durante los proximos 60 dias."] = "Nao ha eventos nos proximos 60 dias.",
            ["Proximos 60 dias"] = "Proximos 60 dias",
            ["Agenda unificada"] = "Agenda unificada",
            ["Tarjetas, gastos, cobros, metas y retornos en un solo lugar."] = "Cartoes, despesas, cobrancas, metas e retornos em um so lugar.",
            ["Configuracion"] = "Configuracao",
            ["Preferencias"] = "Preferencias",
            ["Actualizar preferencias"] = "Atualizar preferencias"
            ,
            ["Gestion premium"] = "Gestao premium",
            ["Control, claridad y crecimiento financiero"] = "Controle, clareza e crescimento financeiro",
            ["Contrasena"] = "Senha",
            ["Olvide mi contrasena"] = "Esqueci minha senha",
            ["Ingresar"] = "Entrar",
            ["Acceso protegido con correo verificado, bloqueo por intentos y sesion segura."] = "Acesso protegido com email verificado, bloqueio por tentativas e sessao segura.",
            ["¿Quieres suscribirte?"] = "Quer assinar?",
            ["Quieres suscribirte?"] = "Quer assinar?",
            ["Acceso seguro"] = "Acesso seguro",
            ["Recuperar contrasena"] = "Recuperar senha",
            ["Te enviaremos un enlace de un solo uso si el correo existe."] = "Enviaremos um link de uso unico se o email existir.",
            ["Enviar enlace"] = "Enviar link",
            ["Volver al ingreso"] = "Voltar ao login",
            ["Proteccion de cuenta"] = "Protecao da conta",
            ["Crear nueva contrasena"] = "Criar nova senha",
            ["Usa una clave fuerte y unica para este sistema."] = "Use uma senha forte e unica para este sistema.",
            ["Confirmar contrasena"] = "Confirmar senha",
            ["Actualizar contrasena"] = "Atualizar senha",
            ["Preferencias actualizadas."] = "Preferencias atualizadas.",
            ["Olvidaste tu contrasena?"] = "Esqueceu sua senha?",
            ["Escribe tu correo registrado y te enviaremos un enlace seguro de un solo uso para crear una nueva contrasena."] = "Digite seu email registrado e enviaremos um link seguro de uso unico para criar uma nova senha.",
            ["Recuperar contrasena"] = "Recuperar senha",
            ["Nuevo prestamo"] = "Novo emprestimo",
            ["Antes de registrar un prestamo debes"] = "Antes de registrar um emprestimo voce deve",
            ["crear al menos una persona"] = "criar pelo menos uma pessoa",
            ["Todas las fechas"] = "Todas as datas",
            ["Prestado desde"] = "Emprestado desde",
            ["Prestado hasta"] = "Emprestado ate",
            ["Limpiar filtros"] = "Limpar filtros",
            ["Capital prestado (activos)"] = "Capital emprestado (ativos)",
            ["Saldo de capital por cobrar"] = "Saldo de capital a receber",
            ["Interes pendiente"] = "Juros pendentes",
            ["Capital"] = "Capital",
            ["Saldo"] = "Saldo",
            ["Tasa"] = "Taxa",
            ["Pagado"] = "Pago",
            ["Control"] = "Controle",
            ["No tienes prestamos registrados."] = "Voce nao tem emprestimos registrados.",
            ["Fecha del prestamo"] = "Data do emprestimo",
            ["Interes mensual (%)"] = "Juros mensal (%)",
            ["Interes mensual ($)"] = "Juros mensal ($)",
            ["Dia de pago de interes"] = "Dia de pagamento de juros",
            ["Pago del capital (si aplica)"] = "Pagamento do capital (se aplicavel)",
            ["Notas (opcional)"] = "Notas (opcional)",
            ["Registrar prestamo"] = "Registrar emprestimo",
            ["Capital y tasa deben ser validos."] = "Capital e taxa devem ser validos.",
            ["Primero crea la persona en el modulo de Personas."] = "Primeiro crie a pessoa no modulo Pessoas.",
            ["Prestamo registrado."] = "Emprestimo registrado.",
            ["Prestamo actualizado."] = "Emprestimo atualizado.",
            ["Abono a capital registrado."] = "Pagamento de capital registrado.",
            ["Pago de interes registrado."] = "Pagamento de juros registrado.",
            ["Pago eliminado del historial."] = "Pagamento removido do historico.",
            ["Prestamo eliminado con todo su historial."] = "Emprestimo excluido com todo o historico.",
            ["Mi portafolio"] = "Minha carteira",
            ["Controla capital, rentabilidad, vencimientos y valor de mercado."] = "Controle capital, rentabilidade, vencimentos e valor de mercado.",
            ["Tipos"] = "Tipos",
            ["Analisis"] = "Analise",
            ["Nueva inversion"] = "Novo investimento",
            ["Debes"] = "Voce deve",
            ["crear un tipo de inversion"] = "criar um tipo de investimento",
            ["antes de registrar una inversion."] = "antes de registrar um investimento.",
            ["Activas"] = "Ativas",
            ["Cerradas"] = "Fechadas",
            ["Limpiar"] = "Limpar",
            ["Capital aportado"] = "Capital aportado",
            ["Valor del portafolio"] = "Valor da carteira",
            ["Ganancia real"] = "Ganho real",
            ["Rentabilidad total"] = "Rentabilidade total",
            ["Valor actual"] = "Valor atual",
            ["Ganancia"] = "Ganho",
            ["Disponible desde"] = "Disponivel desde",
            ["Retorno:"] = "Retorno:",
            ["No tienes inversiones registradas"] = "Voce nao tem investimentos registrados",
            ["Crea la primera para comenzar a medir rentabilidad y vencimientos."] = "Crie o primeiro para comecar a medir rentabilidade e vencimentos.",
            ["Crear inversion"] = "Criar investimento",
            ["Nombre"] = "Nome",
            ["Entidad / plataforma"] = "Entidade / plataforma",
            ["Inicio"] = "Inicio",
            ["Capital inicial"] = "Capital inicial",
            ["Rendimiento"] = "Rendimento",
            ["Fijo"] = "Fixo",
            ["Variable"] = "Variavel",
            ["Tasa (%)"] = "Taxa (%)",
            ["Periodo tasa"] = "Periodo da taxa",
            ["Anual"] = "Anual",
            ["Mensual"] = "Mensal",
            ["Fecha retorno"] = "Data de retorno",
            ["Permanencia (meses)"] = "Permanencia (meses)",
            ["Penalidad retiro (%)"] = "Penalidade de retirada (%)",
            ["Color"] = "Cor",
            ["Icono"] = "Icone",
            ["Renovacion automatica"] = "Renovacao automatica",
            ["Guardar inversion"] = "Salvar investimento",
            ["Revisa los datos de la inversion."] = "Revise os dados do investimento.",
            ["La fecha de retorno no puede ser anterior al inicio."] = "A data de retorno nao pode ser anterior ao inicio.",
            ["Selecciona un tipo de inversion valido."] = "Selecione um tipo de investimento valido.",
            ["Inversion creada."] = "Investimento criado.",
            ["Inversion actualizada."] = "Investimento atualizado.",
            ["La fecha no puede ser anterior al inicio de la inversion."] = "A data nao pode ser anterior ao inicio do investimento.",
            ["No puedes registrar un movimiento futuro."] = "Voce nao pode registrar uma movimentacao futura.",
            ["Valor actual registrado."] = "Valor atual registrado.",
            ["Valoracion eliminada."] = "Valoracao excluida.",
            ["Inversion cerrada."] = "Investimento fechado.",
            ["Inversion reactivada."] = "Investimento reativado.",
            ["Inversion eliminada con su historial."] = "Investimento excluido com seu historico."
            ,
            ["Recibimos una solicitud para restablecer tu contrasena."] = "Recebemos uma solicitacao para redefinir sua senha.",
            ["Restablecer contrasena"] = "Redefinir senha",
            ["Este enlace vence en 30 minutos y solo puede usarse una vez."] = "Este link expira em 30 minutos e so pode ser usado uma vez.",
            ["Verifica tu correo"] = "Verifique seu email",
            ["Confirma que este correo te pertenece para activar el acceso seguro."] = "Confirme que este email pertence a voce para ativar o acesso seguro.",
            ["Verificar correo"] = "Verificar email",
            ["Este enlace vence en 24 horas."] = "Este link expira em 24 horas.",
            ["Si el boton no funciona, copia este enlace:"] = "Se o botao nao funcionar, copie este link:",
            ["Recordatorio:"] = "Lembrete:",
            ["Tu gasto recurrente"] = "Sua despesa recorrente",
            ["Tu ingreso recurrente"] = "Sua receita recorrente",
            ["vence el"] = "vence em",
            ["Debes cobrar a"] = "Voce deve cobrar de",
            ["Hola"] = "Ola",
            ["te recordamos el pago pendiente de tu prestamo. Gracias."] = "lembramos voce do pagamento pendente do seu emprestimo. Obrigado.",
            ["La inversion"] = "O investimento",
            ["tiene retorno esperado el"] = "tem retorno esperado em",
            ["Tu inversion"] = "Seu investimento"
        }
    };

    public string IdiomaActual(ClaimsPrincipal user)
    {
        var idioma = user.FindFirstValue("Idioma");
        return NormalizarIdioma(idioma);
    }

    public string T(string texto, ClaimsPrincipal user) => T(texto, IdiomaActual(user));

    public string T(string texto, string? idioma)
    {
        idioma = NormalizarIdioma(idioma);
        if (idioma == "es") return texto;
        return Traducciones.TryGetValue(idioma, out var dic) && dic.TryGetValue(texto, out var traducido)
            ? traducido
            : texto;
    }

    public string TraducirHtmlVisible(string html, string? idioma)
    {
        idioma = NormalizarIdioma(idioma);
        if (idioma == "es" || string.IsNullOrWhiteSpace(html)) return html;

        var bloquesProtegidos = new List<string>();
        html = Regex.Replace(html, @"<(script|style)\b[\s\S]*?</\1>", match =>
        {
            var token = $"__I18N_BLOCK_{bloquesProtegidos.Count}__";
            bloquesProtegidos.Add(match.Value);
            return token;
        }, RegexOptions.IgnoreCase);

        var salida = new StringBuilder(html.Length);
        var texto = new StringBuilder();
        var enEtiqueta = false;

        foreach (var c in html)
        {
            if (c == '<')
            {
                VolcarTexto();
                enEtiqueta = true;
                salida.Append(c);
                continue;
            }

            if (c == '>')
            {
                enEtiqueta = false;
                salida.Append(c);
                continue;
            }

            if (enEtiqueta)
                salida.Append(c);
            else
                texto.Append(c);
        }

        VolcarTexto();
        var traducido = salida.ToString();
        for (var i = 0; i < bloquesProtegidos.Count; i++)
            traducido = traducido.Replace($"__I18N_BLOCK_{i}__", bloquesProtegidos[i], StringComparison.Ordinal);
        return traducido;

        void VolcarTexto()
        {
            if (texto.Length == 0) return;
            salida.Append(TraducirTextoPlano(texto.ToString(), idioma));
            texto.Clear();
        }
    }

    private static string TraducirTextoPlano(string texto, string idioma)
    {
        if (!Traducciones.TryGetValue(idioma, out var dic)) return texto;
        foreach (var par in dic.OrderByDescending(x => x.Key.Length))
            texto = texto.Replace(par.Key, par.Value, StringComparison.OrdinalIgnoreCase);
        return texto;
    }

    public static string NormalizarIdioma(string? idioma) => idioma?.Trim().ToLowerInvariant() switch
    {
        "en" or "en-us" => "en",
        "pt" or "pt-br" => "pt",
        _ => "es"
    };
}
